CFLAGS_synaptics_dsx_i2c.o := -DDEBUG
CFLAGS_synaptics_dsx_rmi_dev.o := -DDEBUG
CFLAGS_synaptics_dsx_fw_update.o := -DDEBUG
CFLAGS_synaptics_dsx_test_reporting.o := -DDEBUG
obj-y +=  synaptics_dsx_i2c.o synaptics_dsx_rmi_dev.o synaptics_dsx_fw_update.o synaptics_dsx_test_reporting.o
