obj-y += tcc353x_monitoring.o
obj-y += tcc353x_monitoring_calculate.o

EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3530/Tcc353xDriver/common
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3530/Tcc353xDriver/api/inc
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3530/Tcc353xDriver/PAL
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3530/Tcc353xDriver/sample/monitoring

