#platform.team@lge.com	2011.01

obj-$(CONFIG_LGE_FELICA) += felica_uart.o felica_i2c.o felica_cal.o felica.o felica_test.o felica_rfs.o felica_pon.o felica_gpio.o felica_rws.o felica_cen.o felica_common.o
