# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_ARIZONA)	+= switch-arizona.o
obj-$(CONFIG_SWITCH_MAX1462X) += hds_max1462x.o
obj-$(CONFIG_INPUT_MAX14688) += hds_max14688.o
