obj-$(CONFIG_MACH_MSM8974_G2_KR) += board-8974-g2-kr.o board-8974-g2-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_ATT) += board-8974-g2-us.o board-8974-g2-att-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_VZW) += board-8974-g2-us.o board-8974-g2-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_SPR) += board-8974-g2-us.o board-8974-g2-spr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_TMO_US) += board-8974-g2-us.o board-8974-g2-tmo_us-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_DCM) += board-8974-g2-dcm.o board-8974-g2-dcm-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_KDDI) += board-8974-g2-kddi.o board-8974-g2-kddi-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_OPEN_COM) += board-8974-g2-com.o board-8974-g2-open_com-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_OPEN_AME) += board-8974-g2-open_ame.o board-8974-g2-open_ame-gpiomux.o
# OPT_AU will use OPEN_COM Board files. In future OPT related changes will be done under OPT_AU tag.
obj-$(CONFIG_MACH_MSM8974_G2_OPT_AU) += board-8974-g2-au.o board-8974-g2-opt_au-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_TEL_AU) += board-8974-g2-tel_au.o board-8974-g2-tel_au-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G2_CA) += board-8974-g2-ca.o board-8974-g2-ca-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_Z_KR) += board-8974-z-kr.o board-8974-z-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_Z_SPR) += board-8974-z-us-spr.o board-8974-z-us-spr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_Z_TMO_US) += board-8974-z-us-tmo.o board-8974-z-us-tmo-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_Z_KDDI) += board-8974-z-kddi.o board-8974-z-kddi-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_Z_ATT_US) += board-8974-z-us-att.o board-8974-z-us-att-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_Z_OPEN_COM) += board-8974-z-open-com.o board-8974-z-open-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_Z_CTC_CN) += board-8974-z-ctc.o board-8974-z-ctc-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_VU3_KR) += board-8974-vu3-kr.o board-8974-vu3-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_B1_KR) += board-8974-b1-kr.o board-8974-b1-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_B1W) += board-8974-b1w.o board-8974-b1w-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_TIGERS_KR) += board-8974-tigers-kr.o board-8974-tigers-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_Z_CA) += board-8974-z-ca.o board-8974-z-ca-gpiomux.o

obj-$(CONFIG_LGE_BLUETOOTH) += board-8974-g2-rfkill.o
