obj-y += tcpal_android.o
obj-y += tcpal_i2c.o

EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535/Tcc353xDriver/common
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535/Tcc353xDriver/api/inc
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535/Tcc353xDriver/PAL
EXTRA_CFLAGS += -Idrivers/broadcast/oneseg/tcc3535/Tcc353xDriver/sample/monitoring

