#
# Makefile for the TDMB FC8050 drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= broadcast_fc8050_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= broadcast_fc8050.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= tdmb_tunerbbdrv_fc8050.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= bbm.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050_bb.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050_demux.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050_hpi.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050_i2c.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050_isr.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050_ppi.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050_spi.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050_tun.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fci_hal.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fci_i2c.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fci_oal.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fci_tun.o
