obj-y += src/

EXTRA_CFLAGS += -Idrivers/char/tcc3530/Tcc353xDriver/common
EXTRA_CFLAGS += -Idrivers/char/tcc3530/Tcc353xDriver/api/inc
EXTRA_CFLAGS += -Idrivers/char/tcc3530/Tcc353xDriver/PAL
EXTRA_CFLAGS += -Idrivers/char/tcc3530/Tcc353xDriver/sample/monitoring

